import { CommonModule } from '@angular/common';
import { Component, signal } from '@angular/core';

const tableHeaders = [
  'Object Code',
  'Resource Summary',
  'BASE-A-G',
  'BASE-AP',
  'BASE-ATTND',
  'BASE-CASE',
  'BASE-CS AP',
  'BASE-CSM',
  'BASE-ELD',
  'BASE-GC',
  'BASE-LNC',
  'BASE-LRE',
  'BASE-PPL',
  'BASE-TEACH',
  'CEN-CK',
  'CEN-COUNS',
  'CEN-CTS',
  'CEN-LSA',
  'CEN-NEWC',
  'CEN-NURSE',
];

const data = [
  {
    objectCode: '1119 Teacher On Spec Assin School',
    resourceSummary: 0.0,
    base_a_g: '',
    base_ap: '',
    base_attnd: '',
    base_case: '',
    base_cs_ap: '',
    base_csm: '',
    base_eld: '',
    base_gc: '',
    base_lnc: '',
    base_lre: '',
    base_ppl: '',
    base_teach: '',
    cen_ck: '',
    cen_couns: '',
    cen_cts: '',
    cen_lsa: '',
    cen_newc: '',
    cen_nurse: '',
  },
  {
    objectCode: '1120 Teachers Salaries Stipends',
    resourceSummary: 101149.92,
    base_a_g: '',
    base_ap: '',
    base_attnd: '',
    base_case: '',
    base_cs_ap: '',
    base_csm: '',
    base_eld: '',
    base_gc: '',
    base_lnc: '',
    base_lre: '',
    base_ppl: '',
    base_teach: '',
    cen_ck: '',
    cen_couns: '',
    cen_cts: '',
    cen_lsa: '',
    cen_newc: '',
    cen_nurse: '',
  },
  {
    objectCode: '1150 Teachers Substitutes',
    resourceSummary: 0.0,
    base_a_g: '',
    base_ap: '',
    base_attnd: '',
    base_case: '',
    base_cs_ap: '',
    base_csm: '',
    base_eld: '',
    base_gc: '',
    base_lnc: '',
    base_lre: '',
    base_ppl: '',
    base_teach: '',
    cen_ck: '',
    cen_couns: '',
    cen_cts: '',
    cen_lsa: '',
    cen_newc: '',
    cen_nurse: '',
  },
  {
    objectCode: '1320 Supv&adm Salaries Stipends',
    resourceSummary: 0.0,
    base_a_g: '',
    base_ap: '',
    base_attnd: '',
    base_case: '',
    base_cs_ap: '',
    base_csm: '',
    base_eld: '',
    base_gc: '',
    base_lnc: '',
    base_lre: '',
    base_ppl: '',
    base_teach: '',
    cen_ck: '',
    cen_couns: '',
    cen_cts: '',
    cen_lsa: '',
    cen_newc: '',
    cen_nurse: '',
  },
];

@Component({
  selector: 'app-certificated-salaries',
  standalone: true,
  imports: [CommonModule],
  templateUrl: './certificated-salaries.component.html',
  styleUrl: './certificated-salaries.component.scss',
})
export class CertificatedSalariesComponent {
  tableHeaders = signal(tableHeaders);
  data = signal(data);
}
