import { CommonModule, CurrencyPipe } from '@angular/common';
import { Component, signal } from '@angular/core';
import { initFlowbite } from 'flowbite';
import { CertificatedSalariesComponent } from './components/certificated-salaries/certificated-salaries.component';
import { InProgressComponent } from '../../../shared/components/in-progress/in-progress.component';

const tableHeaders = [
  '',
  'Summary',
  'BASE-A-G',
  'BASE-AP',
  'BASE-ATTND',
  'BASE-CASE',
  'BASE-CS AP',
  'BASE-CSM',
  'BASE-ELD',
  'BASE-GC',
  'BASE-LNC',
  'BASE-LRE',
  'BASE-PPL',
  'BASE-TEACH',
  'CEN-CK',
  'CEN-COUNS',
  'CEN-CTS',
  'CEN-LSA',
  'CEN-NEWC',
  'CEN-NURSE',
];

const data = [
  {
    category: 'FTE Allocation',
    summary: 93.13,
    base_a_g: 1.4,
    base_ap: 2.0,
    base_attnd: 1.0,
    base_case: 0.5,
    base_cs_ap: 1.0,
    base_csm: 1.0,
    base_eld: 4.6,
    base_gc: 2.0,
    base_lnc: 1.6,
    base_lre: 0.4,
    base_ppl: 1.2,
    base_teach: 1.0,
    cen_ck: 46.2,
    cen_couns: 3.0,
    cen_cts: 2.5,
    cen_lsa: 1.33,
    cen_newc: 0.5,
    cen_nurse: 1.0,
  },
  {
    category: 'Resource Allocation',
    summary: 3593707.76,
    base_a_g: '',
    base_ap: '',
    base_attnd: '',
    base_case: '',
    base_cs_ap: '',
    base_csm: '',
    base_eld: '',
    base_gc: '',
    base_lnc: '',
    base_lre: '',
    base_ppl: '',
    base_teach: 4688489.9,
    cen_ck: 58003.56,
    cen_couns: 255820.83,
    cen_cts: 56120.24,
    cen_lsa: '',
    cen_newc: '',
    cen_nurse: '',
  },
  {
    category: 'Budgeted FTE',
    summary: 74.94,
    base_a_g: 9.2,
    base_ap: 2.0,
    base_attnd: 1.0,
    base_case: 1.0,
    base_cs_ap: 0.5,
    base_csm: 0.5,
    base_eld: 2.0,
    base_gc: 2.0,
    base_lnc: '',
    base_lre: '',
    base_ppl: 1.2,
    base_teach: 43.7,
    cen_ck: 3.0,
    cen_couns: '',
    cen_cts: '',
    cen_lsa: 0.5,
    cen_newc: '',
    cen_nurse: '',
  },
  {
    category: 'Budgeted Resource',
    summary: 2685980.55,
    base_a_g: '',
    base_ap: '',
    base_attnd: '',
    base_case: 98471.38,
    base_cs_ap: 128896.76,
    base_csm: 1990.15,
    base_eld: 18626.63,
    base_gc: 127298.96,
    base_lnc: '',
    base_lre: 127526.08,
    base_ppl: '',
    base_teach: '',
    cen_ck: '',
    cen_couns: '',
    cen_cts: '',
    cen_lsa: '',
    cen_newc: '',
    cen_nurse: '',
  },
  {
    category: 'Site Labor Expenditures',
    summary: 7120576.77,
    base_a_g: 874963.73,
    base_ap: 240909.55,
    base_attnd: '',
    base_case: '',
    base_cs_ap: '',
    base_csm: '',
    base_eld: '',
    base_gc: '',
    base_lnc: '',
    base_lre: '',
    base_ppl: '',
    base_teach: '',
    cen_ck: '',
    cen_couns: '',
    cen_cts: '',
    cen_lsa: '',
    cen_newc: '',
    cen_nurse: '',
  },
  {
    category: 'Site Non-labor Expenditures',
    summary: 2685980.55,
    base_a_g: '',
    base_ap: '',
    base_attnd: '',
    base_case: '',
    base_cs_ap: '',
    base_csm: '',
    base_eld: '',
    base_gc: '',
    base_lnc: '',
    base_lre: '',
    base_ppl: '',
    base_teach: '',
    cen_ck: '',
    cen_couns: '',
    cen_cts: '',
    cen_lsa: '',
    cen_newc: '',
    cen_nurse: '',
  },
  {
    category: 'FTE Surplus/Deficit',
    summary: 18.19,
    base_a_g: -7.8,
    base_ap: '',
    base_attnd: 1.0,
    base_case: -0.5,
    base_cs_ap: 0.5,
    base_csm: 4.6,
    base_eld: '',
    base_gc: '',
    base_lnc: 1.6,
    base_lre: -0.8,
    base_ppl: '',
    base_teach: 2.5,
    cen_ck: '',
    cen_couns: '',
    cen_cts: '',
    cen_lsa: '',
    cen_newc: 0.5,
    cen_nurse: '',
  },
  {
    category: 'Resource Surplus/Deficit',
    summary: 907727.21,
    base_a_g: '',
    base_ap: '',
    base_attnd: '',
    base_case: '',
    base_cs_ap: '',
    base_csm: '',
    base_eld: '',
    base_gc: '',
    base_lnc: '',
    base_lre: '',
    base_ppl: '',
    base_teach: '',
    cen_ck: '',
    cen_couns: '',
    cen_cts: '',
    cen_lsa: '',
    cen_newc: '',
    cen_nurse: '',
  },
];

const tabs = [
  {
    id: 'profile',
    label: 'Profile',
    content: "Profile tab's associated content",
  },
  {
    id: 'dashboard',
    label: 'Dashboard',
    content: "Dashboard tab's associated content",
  },
  {
    id: 'settings',
    label: 'Settings',
    content: "Settings tab's associated content",
  },
  {
    id: 'contacts',
    label: 'Contacts',
    content: "Contacts tab's associated content",
  },
];

@Component({
  selector: 'app-non-salary-costs',
  standalone: true,
  imports: [
    CommonModule,
    CurrencyPipe,
    CertificatedSalariesComponent,
    InProgressComponent,
  ],
  templateUrl: './non-salary-costs.component.html',
  styleUrl: './non-salary-costs.component.scss',
})
export class NonSalaryCostsComponent {
  tableHeaders = signal(tableHeaders);
  data = signal(data);
  tabs = signal(tabs);

  ngOnInit(): void {
    initFlowbite();
  }
}
